---
- name: 'Configure common parameters of the Clos fabric'
  hosts: fabric
  gather_facts: False
  connection: httpapi
  roles: 
    - common

- name: Configure Leaf devices specific parameters
  hosts: leaf
  gather_facts: False
  connection: httpapi
  roles: 
    - underlay
    - mclag
    - overlay
    - defaultvrf_vxlan

- name: Configure Spine devices specific parameters
  hosts: spine
  gather_facts: False
  connection: httpapi
  roles: 
    - underlay
    - overlay
