---
# tasks file for mclag
- name: "Breakout any port if needed"
  sonic_port_breakout:
    config:
    - name: '{{item}}'
      mode: '{{breakout_ports}}'
  loop: '{{breakout_ports}}'
  when: breakout_ports is defined

- name: Bringup server connected ports 
  sonic_interfaces:
    config:
      - name: "{{ item['name'] }}"
        enabled: true
    state: merged
  loop: "{{server_ports}}" 

- name: Bringup MCLAG peer ports 
  sonic_interfaces:
    config:
      - name: "{{ item }}"
        enabled: true
    state: merged
  loop: "{{mclag.peer_ports}}" 

- name: Associate server ports to port channel
  sonic_lag_interfaces:
    config:
      - name: "{{ item['lag'] }}"
        members:
          interfaces:
            - member: "{{ item['name'] }}"
        mode: static
  loop: "{{server_ports}}" 

- name: Associate MCLAG peer ports to port channel
  sonic_lag_interfaces:
    config:
      - name: "{{ mclag.peer_lag }}"
        members:
          interfaces:
            - member: "{{ item }}"
        mode: static
  loop: "{{mclag.peer_ports}}"   

- name: Configure MCLAG parameters
  sonic_mclag:
    config:
      domain_id: '{{mclag.domain}}'  
      peer_address: "{{loopbacks[0]['mlag_peer']}}"
      source_address: "{{loopbacks[0]['ip']}}"
      peer_link: '{{mclag.peer_lag}}'
      keepalive: 1
      session_timeout: 3
      members:
        portchannels:
          - lag: "{{item['lag']}}"
  loop: "{{server_ports}}" 

